package co.com.mippes.enumerator;

public enum CodigoServicio {

	CONSULTA_DIRECCIONAMIENTO,
	REPORTAR_PROGRAMACION,
	REPORTAR_ANULACION,
	REPORTAR_ENTREGADO,
	REPORTAR_REPORTE_ENTREGADO,
	CONSULTA_PROGRAMACIONES,
	CONSULTA_ENTREGAS,
	CONSULTA_REPORTE_ENTREGAS;	
	
}
